name: CI

on:
  push:
    branches: 
      - master
      - dev
      - transifex

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CI: true
    steps:
    - name: Checkout branch `dev`
      uses: actions/checkout@v2
      with:
        ref: dev
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: Fetch all branches
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    - name: Install `vuepress` using `npm`
      run: |
        npm i -g vuepress
    - name: Checkout branch `transifex` files into branch `dev`
      run: |
        chmod +x ./fetch_transifex.sh
        ./fetch_transifex.sh
    - name: Build documents & Deploy to Github pages (branch `gh-pages`)
      env:
        DEFAULT_REPO:  https://github.com/${{ github.repository }}
      run: |
        chmod +x ./deploy.sh
        ./deploy.sh
